cache:
  paths:
  - Example/Pods
before_script:
  - bundle install
  - bundle exec pod install --project-directory=Example
stages:
  - test
  - deploy_cocoapods
deploy_cocoapods:
  script:
    - bundle exec fastlane push
  environment: cocoapods
  when: manual
  only:
    - master
test:
  script:
    - bundle exec fastlane ci
  artifacts:
    paths:
    - fastlane/**/*.xml
    - fastlane/**/*.junit
    - fastlane/**/*.html