before_script:
  - bundle install
  - brew bundle
stages:
  - test
  - deploy
deploy:
  script:
    - bundle exec fastlane push
  when: manual
  only:
    - master
test:
  script:
    - bundle exec fastlane ci
  artifacts:
    paths:
    - fastlane/**/*.xml
    - fastlane/**/*.junit
    - fastlane/**/*.html