osx_image: xcode8
language: objective-c
notifications:
  email: false
before_install:
- gem install bundler
- bundle install
- bundle exec pod repo update --silent
script:
- bundle exec fastlane travis
after_success:
- bash <(curl -s https://codecov.io/bash)
- bundle exec fastlane push
